<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

// use App\StatusUserModel;
use Faker\Generator as Faker;

$factory->define(\App\Job::class, function (Faker $faker) {
    static $i;
    $jobs = [
        'Administrator',
        'Advokat(Pengacara)',
        'Agen rahasia (Mata-mata)',
        'Aktor',
        'Akuntan',
        'Antariksawan (Astronaut, Astronot),',
        'Apoteker',
        'Arsitek',
        'Atlet (atlit)',
        'Bartender (Pramutama bar)',
        'Bidan',
        'Blogger',
        'Buruh',
        'Calo',
        'Camat',
        'Desainer (Perancang)',
        'Direktur',
        'Dokter',
        'Dokter hewan',
        'Dosen',
        'Redaktur',
        'Fotografer (Juru foto)',
        'Gamer',
        'Guide',
        'Guru (Pengajar)',
        'Ilmuwan',
        'Ilustrator',
        'Insinyur',
        'Inspektur',
        'Jaksa',
        'Jurnalis (Wartawan)',
        'Karyawan (Buruh)',
        'Kasir',
        'Kiai (Ulama)',
        'Koki (Juru masak)',
        'Komikus',
        'Kondektur',
        'Konsultan (Pakar runding)',
        'Lurah',
        'Manajer',
        'Marketing',
        'Masinis (Juru mesin)',
        'Model',
        'Montir',
        'Mahasiswa',
        'Nakhoda (Nakoda)',
        'Nelayan',
        'Novelis (Penulis)',
        'Notaris',
        'Operator',
        'Pastor (agama Kristen)',
        'Pedagang',
        'PNS (Pegawai Negeri Sipil)',
        'Pekerja sosial',
        'Pelaut',
        'pelajar',
        'Pelayan',
        'Pelukis',
        'Pemadam kebakaran (Damkar PMK)',
        'Pemahat',
        'Pemain sepak bola',
        'Pemeran (Aktor)',
        'Pemrogram (Pengembang perangkat lunak Programmer)',
        'Penari',
        'Pendeta',
        'Peneliti',
        'Penerjemah',
        'Pengacara (Advokat)',
        'Pengantar surat (Tukang pos)',
        'Pengusaha',
        'Penulis',
        'Penyanyi',
        'Perancang (Desainer)',
        'Perancang grafis (Desainer grafis)',
        'Perawat',
        'Peretas',
        'Perminyakan',
        'Petani',
        'Peternak',
        'Polisi',
        'Politikus',
        'Pramugari',
        'Programmer',
        'Psikiater (Dokter jiwa)',
        'Psikolog (Ahli psikologi)',
        'Pilot (Pengemudi pesawat terbang)',
        'Pramusaji',
        'Pramugara',
        'Presiden',
        'Raja',
        'Ratu',
        'Refractionis Optisen',
        'Resepsionis',
        'Satuan pengamanan (Satpam)',
        'Sekretaris',
        'Selebriti',
        'Seniman',
        'Sopir (Supir)',
        'Tani (Petani)',
        'Tengkulak',
        'TNI',
        'Tukang',
        'Tukang jahit',
        'Tukang kayu',
        'Tukang las',
        'Tukang listrik',
        'Tukang pos (pengantar surat)',
        'Ulama',
        'Ustad',
        'Video-editor',
        'Wartawan (Jurnalis  Pewarta)',
        'Wiraswastawan (Wirausahawan)',
        'Wirausahawan',
        'Youtubers',
        'Zumba Instruktur',
    ];
    $i++;
    return [
        'job' => $jobs[$i - 1]
    ];
});
